/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whoishere;

import javax.swing.*;
import java.awt.*;
import java.util.*;

public class App extends JFrame {
    /**
     * App init point
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new App().init();
        });
    }
    
    private JTextArea output = null;
    
    public void init() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
        this.setTitle("Who the hell is here?");
        this.setPreferredSize(new Dimension(400, 300));
        
        this.output = new JTextArea(5, 20);
        this.output.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(this.output); 
        
        JButton button = new JButton("Who is here?");
        button.addActionListener((evt) -> {
            // Hop off GUI thread to do work
            new Thread(() -> {
                if (isUnix()) {
                    final String output = getFormattedMACs();
                    // Hop back on GUI thread to set text
                    SwingUtilities.invokeLater(() -> {
                        this.output.append(output);
                    });
                }
                else if (isWindows()) {
                    final String output = execCmd("ping /n 1 224.0.0.1") + System.lineSeparator();
                    // Hop back on GUI thread to set text
                    SwingUtilities.invokeLater(() -> {
                        this.output.append(output);
                    });
                }
                else {
                    System.err.println("Unknown OS!");
                }

                // Roomba nonsense
                com.maschel.roomba.RoombaJSSC roomba = new com.maschel.roomba.RoombaJSSCSerial();
                System.err.println("roomba="+roomba);

            }).start();
        });
        
        
        this.add(scrollPane, BorderLayout.CENTER);
        this.add(button, BorderLayout.SOUTH);
        
        this.pack();
        
        this.setVisible(true);
        
    }
    
    public static boolean isWindows() {
        return osName().contains("win");
    }
    
    public static boolean isMac() {
        return osName().contains("mac");
    }
    
    public static boolean isUnix() {
        return osName().contains("nux");
    }
    
    public static String osName() {
        return System.getProperty("os.name").toLowerCase();
    }
    
    public static String execCmd(String cmd) {
        try {
          // Magic. It's Magic.
          java.util.Scanner s = new java.util.Scanner(Runtime.getRuntime().exec(cmd).getInputStream()).useDelimiter("\\A");
          return s.hasNext() ? s.next() : "";
        }
        catch (Exception e) {
          e.printStackTrace();
          return "";
        }
    }
    
    // We use the "ping" utility
    public static java.util.List<String> pingAndGetIpsUnix()
    {
        ArrayList<String> parsed_ips = new ArrayList<>();
        String ping_payload = execCmd("ping -c 3 224.0.0.1");
        for (String line : ping_payload.split(System.lineSeparator())) {
            // Line is like:
            // 64 bytes from 192.168.86.37: icmp_seq=1 ttl=64 time=86.5 ms (DUP!)
            if (!line.contains("bytes from")) {
                continue; // Ignore lines we don;t want (headers, empty lines, etc)
            }
            String[] chunks = line.split(" ");
            // Check to make sure we have at least 4 seperate words, if not continue
            if (chunks.length < 4) {
                continue;
            }
            String ip = chunks[3].replaceAll(":", ""); // A dumb way to get the semicolon at the end off
            // Only add IP if new
            if (!parsed_ips.contains(ip)) {
                parsed_ips.add(ip);
            }
        }
        
        return parsed_ips;
    }
    
    // We use the "arp" utility, this returns a map from IP => MAC
    public static HashMap<String, String> getArpTableUnix()
    {
        HashMap<String, String> map = new HashMap<>();
        String arp_payload = execCmd("arp -a");
        
        for (String line : arp_payload.split(System.lineSeparator())) {
            String[] chunks = line.split(" ");
            if (chunks.length < 4) {
                continue; // We ignore any line with fewer than 4 words
            }
            
            String hostname = chunks[0];
            String ip = chunks[1];
            String mac = chunks[3];
            
            if (mac.equals("<incomplete>")) {
                continue; // Happens when you have ARP entries on the docker0 interface
            }
            
            if (!map.containsKey(ip)) {
                map.put(ip, mac);
            }
        }
        
        return map;
    }
    
    public static String getFormattedMACs()
    {
        if (isUnix()) {
            StringBuilder sb = new StringBuilder();
            HashMap<String, String> ips_and_macs = getArpTableUnix();
            for (String mac : ips_and_macs.values()) {
                sb.append(mac);
                sb.append(System.lineSeparator());
            }
            
            return sb.toString();
        }
        else {
            return "Idk? Bluescreening in 3, 2, 1...";
        }
    }
    
}
