/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whoishere;

import javax.swing.*;
import java.awt.*;

public class App extends JFrame {
    /**
     * App init point
     */
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            new App().init();
        });
    }
    
    private JTextArea output = null;
    
    public void init() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
        
        this.output = new JTextArea(5, 20);
        this.output.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(this.output); 
        
        JButton button = new JButton("Who is here?");
        button.addActionListener((evt) -> {
          this.output.append("BUTTON!" + System.lineSeparator());
        });
        
        
        this.add(this.output, BorderLayout.CENTER);
        this.add(button, BorderLayout.SOUTH);
        
        this.setVisible(true);
        
    }
}
